spring:
  mail:
    host: smtp.126.com
    username: hc_monitor888@126.com
    password: "RUIXCVZMVGWBLOXW"
    port: 465
    protocol: smtps

    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
        #表示开启 DEBUG 模式，这样，邮件发送过程的日志会在控制台打印出来，方便排查错误
        debug: true
