server:
  port: 80

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://hadoop102:3306/ssm_db
      username: "root"
      password: "123456"
  boot:
    admin:
      client:
        url: http://localhost:8080


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto

mybatis:
  configuration:
    map-underscore-to-camel-case: true # 驼峰和_转换


management:
  info:
    env:
      enabled: true
  endpoint:  # 开发的端点
    health:
      show-details: always
  endpoints:
    web:
      exposure:
       # include: health,info
        include: "*" #开放的端点
    enabled-by-default: true # 所有的端点都开放,默认是true

info:  # info端点
  appName: @artifactId@
  auther: itheima
  version: @project.version@
  company: 传智教育