server:
  port: 80

spring:
  activemq:
    broker-url: tcp://localhost:61616
  jms:
    pub-sub-domain: true # 使用发布订阅模型
    template:
      default-destination: itheima
  rabbitmq:
    host: localhost
    port: 5673
  # kafka
  kafka:
    bootstrap-servers: hadoop102:9092,hadoop103:9092,hadoop104:9092
    consumer:
      group-id: group1
