spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: "123456"
    url: jdbc:mysql://hadoop102:3306/ssm_db
    type: com.alibaba.druid.pool.DruidDataSource

# 设置mp相关的配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl