
enterprise:
  name: itcast
  age: 16
  tel: 4006184000
  subject:
    - java
    - 前端
    - 大数据

# 设置起用的环境
spring:
  profiles:
    active: ${profile.active}
---
# 开发环境
enterprise:
  name: itcast
  age: 16
  tel: 4006184000
  subject:
    - java
    - 前端
    - 大数据

spring:
  config:
    activate:
      on-profile: dev
server:
  port: 80
---
# 生产环境
enterprise:
  name: itcast
  age: 16
  tel: 4006184000
  subject:
    - java
    - 前端
    - 大数据

server:
  port: 81
spring:
  profiles: pro

---
# 测试环境
enterprise:
  name: itcast
  age: 16
  tel: 4006184000
  subject:
    - java
    - 前端
    - 大数据

server:
  port: 82
spring:
  profiles: test

