country: china
province: beijing
city: beijing
area: haidian

port: 8080

party: true

birthday: 1949-10-01

user:
  name: itcast
  age: 16


user2:
  name: itcast
  age: 16

likes:
  - basketball
  - game
  - music
  - sleep

likes2: [game, music, sleep]

users:
  - name: zhangsan
    age: 18
  - name: lisi
    age: 17

users2:
  -
    name: zhangsan
    age: 18
  -
    name: lisi
    age: 18

users3: [{name:age}, {name:lisi,age:18}]
server:
  port: 80

baseDir: c:\windows

# 使用${属性名}引用数据
tempDir: ${baseDir}\temp

# 使用引号包裹的字符串, 会转义
tempDir2: "${baseDir}\temp"


